### ISSUE TITLE
Convert Module Name to CertificateDsc

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/CertificateDsc#114]
As per recent DSC Resource Naming guidelines changes:
https://github.com/PowerShell/DscResources/blob/master/Naming.md

**Comment by timhaintz** [comment]
Sign me up. Thanks. :octocat:

**Comment by PlagueHO** [comment]
All yours! Thanks @timhaintz !

**Comment by PlagueHO** [comment]
Maybe do this one second, because I wan't to try and get a couple of the open PR's for this one (#119, #117, #108) through first. I'll try and get these moving again this weekend. I'm going to do the PR for #119 tonight.

**Comment by timhaintz** [comment]
Morning @PlagueHO yell out (bump) when you get all of your PR's done and I can have a look at this one too. Thanks.

**Comment by PlagueHO** [comment]
Thanks @timhaintz - I'll give the other submitters a couple of days and if nothing happens we'll just move forward with the rename.

**Comment by timhaintz** [comment]
@PlagueHO I noticed #119 got merged. Did you want me to wait for the others? If it messes up the process me going ahead, happy to wait. Up to you. Thanks.

**Comment by PlagueHO** [comment]
Hi @timhaintz - it looks like the other PR's aren't going to go through anytime soon, so maybe just go ahead and do this one. :grin:

I'm not sure when @kwirkykat will get a chance to do the repo rename though, so no rush! Thanks again for helping out (I've had almost no time at all lately to do anything DSC - too busy with day job :cry:)

**Comment by timhaintz** [comment]
No worries @PlagueHO will get onto it this weekend. 
I saw you released the updated Cosmos DB Module. Nice! You have been busy. :D
Thanks for your help with all of this. Great way to learn the eco system.

**Comment by PlagueHO** [comment]
Thanks again for all your help @timhaintz ! Nice to see attention on the CosmosDB module! :grin: I'm at the MVP summit in US all this week so might get a bit of "non-work" time to catch up on DSC stuff (hopefully).

**Comment by timhaintz** [comment]
Question about $script:ModulesToTest in the file ModuleConflict.Tests.ps1, it refers to the xDFS module. I've just renamed that one to DFSDsc but it hasn't been merged with master yet. Do you want me to update them to what they will be or keep them as they currently are? Thanks @PlagueHO . Have a great time at the MVP summit. Would love to go one day. :)

**Comment by PlagueHO** [comment]
Completed!
