### ISSUE TITLE
xCertificateExport: pfx with matchsource enabled errors

### ISSUE THREAD

**Issue by hackjammer** [PowerShell/CertificateDsc#116]
The following line throws an error:
https://github.com/PowerShell/xCertificate/blob/4475c79cb3aa59b25eefacf48d3c35a717722c96/Modules/xCertificate/DSCResources/MSFT_xCertificateExport/MSFT_xCertificateExport.psm1#L446

As per the documentation of this method, the second parameter should be a string, not a credential object:
https://msdn.microsoft.com/en-us/library/ms148499(v=vs.110).aspx

Windows Server 2012
Powershell 5.1

**Comment by hackjammer** [comment]
As per the integration tests, there is a version that supports a securestring as well - I suggest we use this:

https://msdn.microsoft.com/en-us/library/ms148441(v=vs.110).aspx

**Comment by PlagueHO** [comment]
Thanks for raising this @hackjammer - great catch!

**Comment by PlagueHO** [comment]
Hi @hackjammer - unfortunately the X509Certificate2Collection.Import Method does not support SecureString - only string. So you'll need to use `$Password.GetNetworkCredential().Password` to return the password. I'll add the info in the PR comments.
