### ISSUE TITLE
xPfxImport: Parameter Description

### ISSUE THREAD

**Issue by bennbatt8112** [PowerShell/CertificateDsc#125]
**Details of the scenario you tried and the problem that is occurring:**
Hi, mainly looking to clarify the descriptions inside this DSC configuration.. I'm sure the code is fine.

"Path" - _The Windows Certificate Store Location to import the PFX file to._
"Location" - _The Windows Certificate Store Location to import the PFX file to._
"Store - _The Windows Certificate Store Name to import the PFX file to._

My understanding is that "Path" should actually point to the path of the .PFX file you are trying to import.. but maybe I'm missing something.

**The DSC configuration that is using the resource (as detailed as possible):**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Master

Thanks!
Bennett

**Comment by PlagueHO** [comment]
Hi @bennbatt8112 - looks like we have an issue with the documentation here - good catch. The `Path` should actually read something like "The path to the PFX file to import to the Windows Certificate Store". So you are quite correct.

I'll submit a PR to get this fixed once the other PR's are through.
