### ISSUE TITLE
Azure KeyVault as PFX Source

### ISSUE THREAD

**Issue by craig-martin** [PowerShell/CertificateDsc#13]
It would be cool if xPfxImport could import a PFX from Azure Key Vault
(https://azure.microsoft.com/en-us/documentation/articles/key-vault-get-started/#add)

I might be converting a DSC configuration to use the Azure VM DSC Extension, and would like to use Key Vault to store the certificates, so might work on this soon.

**Comment by briantist** [comment]
@craig-martin that sounds like a great idea. I don't have enough experience with Azure or Azure DSC to work on this or test it. My current employer doesn't use Azure, but I'll be starting a new job in January at a company that does, so I'll definitely keep this in mind. 

If you start work on it, please let me know, that way I don't duplicate your effort (and maybe we can work together on it).

**Comment by PlagueHO** [comment]
Is this feature still needed? I think you can now import certificates from Key Vault directly into Azure VMs via the ARM template.

**Comment by craig-martin** [comment]
Thanks for the prompt, I do not need this anymore.
