### ISSUE TITLE
Thumbprint is not a valid hash

### ISSUE THREAD

**Issue by llowevad** [PowerShell/CertificateDsc#160]
#### Details of the scenario you tried and the problem that is occurring
Using PFXImport I am getting an invalid hash error on the thumbprint. I believe this is coming from the validateset on test-thumbprint. I am able to run it manually on the server and 3 of the 8 valid algorithms so the hash below as valid, yet I cannot get past the test when running under DSC LCM.

And since this test happens on the parameter, it doesn't even get to check if the certificate is already installed because it fails before it can check for compliance.

Using PFXImport and I am getting the following error

"InnerException":  {

                                             "Message":  "Cannot validate argument on parameter \u0027Thumbprint\u0027. System.InvalidOperationException: \u0027‎96da511b6198f6d699dd33d24c3b233b5f73cdc7\u0027 is not a valid hash.",

                                             "ParameterName":  "Thumbprint",

                                             "ParameterType":  "string",

                                             "TypeSpecified":  "string",

                                             "ErrorId":  "ParameterArgumentValidationError",

                                             "Line":  0,

                                             "Offset":  0,

                                             "CommandInvocation":  "System.Management.Automation.InvocationInfo",

                                             "ErrorRecord":  "Cannot validate argument on parameter \u0027Thumbprint\u0027. System.InvalidOperationException: \u0027‎96da511b6198f6d699dd33d24c3b233b5f73cdc7\u0027 is not a valid hash.",

                                             "WasThrownFromThrowStatement":  false,

                                             "Data":  "System.Collections.ListDictionaryInternal",

                                             "InnerException":  "System.Management.Automation.RuntimeException: System.InvalidOperationException: \u0027‎96da511b6198f6d699dd33d24c3b233b5f73cdc7\u0027 is not a valid hash. ---\u003e System.Exception: System.InvalidOperationException: \u0027‎96da511b6198f6d699dd33d24c3b233b5f73cdc7\u0027 is not a valid hash.\r\n   --- End of inner exception stack trace ---\r\n   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)\r\n   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)\r\n   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)\r\n   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)\r\n   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)\r\n   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)\r\n   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)\r\n   at System.Management.Automation.ScriptBlock.\u003c\u003ec__DisplayClass57_0.\u003cInvokeWithPipe\u003eb__0()\r\n   at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)\r\n   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)\r\n   at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)\r\n   at System.Management.Automation.ValidateScriptAttribute.ValidateElement(Object element)\r\n   at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)",

                                             "TargetSite":  "System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject] Invoke(System.Collections.IEnumerable)",

                                             "StackTrace":  "   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)\r\n   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)\r\n   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)\r\n   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)\r\n   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)\r\n   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)\r\n   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.ExecuteCommand(PowerShell powerShell, ResourceModuleInfo resInfo, String operationCmd, List`1 acceptedProperties, CimInstance nonResourcePropeties, CimInstance resourceConfiguration, LCMDebugMode debugMode, PSInvocationSettings pSInvocationSettings, UInt32\u0026 resultStatusHandle, Collection`1\u0026 result, ErrorRecord\u0026 errorRecord, PSModuleInfo localRunSpaceModuleInfo)",

                                             "HelpLink":  null,

                                             "Source":  "System.Management.Automation",

                                             "HResult":  -2146233087

                                         },

#### Verbose logs showing the problem
I am using azure automation, I do not have verbose logs. The error above provides all the details I have.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
PfxImport $CertResourceName
                            {
                                Thumbprint = $webApp2.CertificateThumbprint
                                Path       = $webApp2.CertificatePath
                                Location   = "LocalMachine"
                                Store      = "WebHosting"
                                Credential = $ParamAccountCertificate
                                DependsOn  = "[SPInstallPrereqs]InstallPreReqs"
                            }
```

#### The operating system the target node is running
This is the latest Windows Server 2016 datacenter image on azure

Version 1607
Build 14393.2430

#### Version and build of PowerShell the target node is running
5.1.14393.2430

#### Version of the DSC module that was used ('dev' if using current dev branch)
4.1

**Comment by PlagueHO** [comment]
Hi @llowevad ,

Thanks for raising this. Do you know which algorithm was used to generate the thumbprint?

We did add some additional algorithm support in 4.1.0.0, but there must be some others that aren't supported yet. I'll look into it as soon as I can (this week).

**Comment by PlagueHO** [comment]
@llowevad - is it possible that this issue is the same as this one here: https://github.com/PowerShell/CertificateDsc/issues/153 ? If you try and import this certificate using `Import-PfxCertificate` on the WS 2016 1607 machine above does it succeed?

**Comment by llowevad** [comment]
Here I run the Test-Thumbprint manually. I adjusted the code to print out good and bad matches. Green are positive matches, which should result in true (meaning the thumbprint) should of passed

[cid:image001.png@01D448F2.9252C350]

Yes, import-pfxcertificate works
Import-PfxCertificate -FilePath "C:\Binaries\Certificates\Contoso_com.pfx" -CertStoreLocation "Cert:\LocalMachine\WebHosting" -Password $pwd

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by llowevad** [comment]
Looks like it was a data issue. I checked for Unicode characters previously but did not see any in the checks that I did. I didn't see it come up in an error message until I removed the validateset's manually for both thumbprint and certpath. When I did I seen the following in an error...

![pfximporterror](https://user-images.githubusercontent.com/8823690/45312526-5246de80-b4fa-11e8-91bd-1465d418ef22.jpg)

I went into my variable definitions and placed the cursor between the " and the C and hit backspace... and it removed the hidden character, Make sure to double check for Unicode characters... You can close this case.

**Comment by PlagueHO** [comment]
Oh right! Cool - thanks for the update @llowevad - that is a sneaky one. I'll close this.
