### ISSUE TITLE
CertReq Idempotency?

### ISSUE THREAD

**Issue by darkonejr** [PowerShell/CertificateDsc#166]
Is there a way to use CertReq in an idempotent way?  I.E.  only request/accept the cert if it can't find it, or it's invalid.  I'd even be willing to live with something that only satisfies the first condition.

**Comment by PlagueHO** [comment]
Hi @darkonejr - the CertReq resource does already behave this way. It looks for a valid cert that matches the subject and issued by the specified CA. If a matching cert is found then it will compare things like SAN, Template and Friendly Name. If any of these don't match then the cert is considered to be different and a new one requested.

Thinking about this it would probably be worth comparing on EKU and KU as well. But that could be for a later release.

**Comment by darkonejr** [comment]
Yeah, I wrote this before I discovered #163 ... that's what's breaking the idempotency for me.
