### ISSUE TITLE
Cannot add Cert to CurrentUser/My

### ISSUE THREAD

**Issue by joshan1120** [PowerShell/CertificateDsc#167]
#### Details of the scenario you tried and the problem that is occurring

I need to add a Cert to the "CurrentUser\My" location. It works perfect when adding to "LocalMachine\My" but I need it to be in "CurrentUser. It throws no errors, but the cert simply is not there. If I only change the line"

Location = 'LocalMachine'
to 
Location = 'CurrentUser'

The cert if not there. If I leave as LocalMachine the cert is there as expected.

#### Verbose logs showing the problem
The logs don't show the problem, they show it being successful, but there cert is not there!

VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer LaptopName with user sid S-1-6-23-2392256083-xxxxxxxxx-xxxxxxxxx-xxxxx.
VERBOSE: [NUSLLR90H5L8S]: LCM:  [ Start  Set      ]
VERBOSE: [NUSLLR90H5L8S]: LCM:  [ Start  Resource ]  [[PfxImport]VpnCert.pfx]
VERBOSE: [NUSLLR90H5L8S]: LCM:  [ Start  Test     ]  [[PfxImport]VpnCert.pfx]
VERBOSE: [LaptopName ]:                            [[PfxImport]VpnCert.pfx] Get-TargetResource: Getting Pfx existence 'xxxx' in 'Cert:\CurrentUser\My'. (PI0001
)
VERBOSE: [LaptopName ]:                            [[PfxImport]VpnCert.pfx] 
Get-TargetResource: Certificate 'xxx' with private key is found in 'Cert:\CurrentUser\My'. (PI0002)
VERBOSE: [LaptopName ]:                            [[PfxImport]VpnCert.pfx] 
Test-TargetResource: Testing Pfx 'xxx' existence in 'Cert:\CurrentUser\My'. (PI0005)
VERBOSE: [NUSLLR90H5L8S]: LCM:  [ End    Test     ]  [[PfxImport]VpnCert.pfx]  in 0.5190 seconds.
VERBOSE: [NUSLLR90H5L8S]: LCM:  [ Skip   Set      ]  [[PfxImport]VpnCert.pfx]
VERBOSE: [NUSLLR90H5L8S]: LCM:  [ End    Resource ]  [[PfxImport]VpnCert.pfx]
VERBOSE: [NUSLLR90H5L8S]: LCM:  [ End    Set      ]
VERBOSE: [NUSLLR90H5L8S]: LCM:  [ End    Set      ]    in  0.6950 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 1.729 seconds

#### Suggested solution to the issue
The cert should be in Cert Store like it is when I send it to "LocalMachine"

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
PfxImport "VpnCert.exe" {
				Thumbprint = "$($cert.pfxThumbPrint)"
				Path = "C:\Software\Certificates\VpnCert.exe"
				Credential = $PfxCreds
				Location = 'CurrentUser'
				Store = "My"
			}

#### The operating system the target node is running
Win7 64-Bit

#### Version and build of PowerShell the target node is running
Name                           Value                                                                                                                                                                                                  
----                           -----                                                                                                                                                                                                  
PSVersion                      5.0.10586.117                                                                                                                                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                
BuildVersion                   10.0.10586.117                                                                                                                                                                                         
CLRVersion                     4.0.30319.42000                                                                                                                                                                                        
WSManStackVersion              3.0                                                                                                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                    
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)

dev, downloaded newest today.

**Comment by joshan1120** [comment]
Here is it working when only changing the Location to "LocalMachine". You can see it doing the set. So the test is telling it the cert exists when it does not when doing "CurrentUser" and it never applies the Set.

VERBOSE: [LaptopName ]:                            [[PfxImport]VpnCert.pfx] Set-TargetResource: Setting Pfx 'xxxx' existence in 'Cert:\LocalMachine\My'. (PI000
6)
VERBOSE: [LaptopName ]:                            [[PfxImport]VpnCert-Prd2e-ModernSurveyDevAccessClient.pfx] Set-TargetResource: Importing Pfx 'C:\Software\CertificatesVpnCert.pfx' into 'Cert:\LocalMachine\My'. (PI0007)
VERBOSE: [LaptopName ]: LCM:  [ End    Set      ]  [[PfxImport]VpnCert.pfx]  in 1.1570 seconds.

**Comment by PlagueHO** [comment]
Hi There @joshan1120 - when the DSC LCM runs it actually executes under the System account context and isn't executing as you. You can force a resource to run under the context of a different user by adding `PSDscRunAsCredential`. See https://docs.microsoft.com/en-us/powershell/dsc/runasuser

**Comment by joshan1120** [comment]
that makes sense, thank you!!

**Comment by PlagueHO** [comment]
No problem! Happy to help :grin:
