### ISSUE TITLE
CertReq: not idempotent when using Subject with comma-separated-list

### ISSUE THREAD

**Issue by The-real-Urb** [PowerShell/CertificateDsc#173]
When using Subject with multiple key-value pairs, the keys have to be sorted in the same order as retrieved from the active certificate. If not, a new certificate will be generated every time the script is run.

example malfunctioning Subject:
Subject = "CN=xyz.msdn.com, E=xyz@msdn.com, OU=Organisation Unit, O=Organisation, L=Locality, S=State, C=country"

example working Subject:
Subject = "E=xyz@msdn.com, CN=xyz.msdn.com, OU=Organisation Unit, O=Organisation, L=Locality, S=State, C=country"

The solution would be to split the Subject-string in key-value-pairs, sort by key, and compare those .

**Comment by PlagueHO** [comment]
Thank you for raising this @The-real-Urb - I'll sort this over the weekend.

**Comment by wh33ly** [comment]
I think this also relates to the idempotency as the compare doesn't match and a new cert is created. 
https://github.com/PowerShell/CertificateDsc/issues/163
https://github.com/PowerShell/CertificateDsc/issues/166
Still figuring out which parameter is causing this in my case, but also when not using the subject alternate names I keep getting new certs. 

So my guess is that there are a few different issues that can cause the module being idempotent depending on the different use cases.

**Comment by PlagueHO** [comment]
Working on this one now - just needed to improve the quality of the unit tests.
