### ISSUE TITLE
Certificate DS Publish functionality 

### ISSUE THREAD

**Issue by jeffotterpohl** [PowerShell/CertificateDsc#182]
ISSUE TITLE:  PublishCert: Add the ability to publish Certificates to the CA or SubCA Containers

    ISSUE DESCRIPTION (this template):
    Add the ability to publish certificates to Active Directory (AD) RootCA or SubCA containers.

### Description
This resource can be used to publish certificates to Active Directory (AD).  This uses the thumbprint of the specified certificate to compare items currently in Active Directory to ensure the same certificate is not published multiple times in Active Directory.

### Proposed properties
[String] CertificateFullPath (_Key_): Specifies the full path of the certificate to be published.
[String] Ensure (_Write_): Ensures that the certificate is **Present** or **Absent**. Default setting is **Present**
[String] PublishLocation (_Write_): Specify Certificate Authority location where to publish the certificate. Required
 parameters are **RootCA** or **SubCA**.
[String] Thumbprint (_Read_): Specifies the thumbprint associated to the certificate being added or removed.

### Special considerations or limitations
Currently this only publishes certificates to the RootCA and SubCA (CN=Certification Authorities and CN=AIA containers).  All Certificates published to the Certification Authorities is also published to the AIA Container.  On the Absent setting the certificate can only be removed from one container at a time even if the certificate is in both areas.

**Comment by PlagueHO** [comment]
This sounds like a useful resource @jeffotterpohl - however, I'd suggest it might actually be best placed in the [ActiveDirectoryCSDsc](https://github.com/PowerShell/ActiveDirectoryCSDsc) Resource module?

**Comment by jeffotterpohl** [comment]
I will close this out and open an issue on the other ActiveDirectoryCSDsc resource.  Thanks!
