### ISSUE TITLE
AD Publish CRL

### ISSUE THREAD

**Issue by jeffotterpohl** [PowerShell/CertificateDsc#183]
ISSUE TITLE:  PublishCrl: Add the ability to publish CRLs to a desired CA in the CDP Container

    ISSUE DESCRIPTION (this template):
    Add the ability to publish CRLs to Active Directory (AD) in the CDP container.

### Description
This resource can be used to publish CRLs to Active Directory (AD).  This uses the thumbprint of the specified CRL to compare items currently in Active Directory to ensure the same CRL is not published multiple times in the same container in Active Directory.

### Proposed properties
[String] CrlFullPath (_Key_): Specifies the full path of the CRL to be published.
[String] CAName (_Write_): Certificate Authority AD container where to publish the CRL.
[String] Ensure (_Write_): Ensures that the CRL is **Present** or **Absent**. Default setting is **Present**
[String] Thumbprint (_Read_): Specifies the thumbprint associated to the CRL being added or removed.

### Special considerations or limitations
Would need to know what CA under the CDP container you are publishing the CRL to.  Also when Absent is selected it will only delete the CRL from the specified CA container and will not delete all instances of the CRL.

**Comment by PlagueHO** [comment]
This sounds like a useful resource @jeffotterpohl - however, I'd suggest it might actually be best placed in the [ActiveDirectoryCSDsc](https://github.com/PowerShell/ActiveDirectoryCSDsc) Resource module?

**Comment by jeffotterpohl** [comment]
That sounds good, I was talking over with another person and we couldn't decide which one to submit it to.  I will close this out and open an issue on the other ActiveDirectoryCSDsc resource.
