### ISSUE TITLE
CertReq: Creates .inf file, but fails when looking for .req file

### ISSUE THREAD

**Issue by jeremysbrain** [PowerShell/CertificateDsc#184]
First off, thanks in advance...
I'm attempting to create a certificate for a pull server.  I'm very new to DSC in general...
Config:
        CertReq PullCert {
            Credential = $CredDomain
            Subject = 'CN=Pull01, , OU=IT, O=JeremysBrain, L=Chino, S=CA, C=US'
            KeyLength = 2048
            CAServerFQDN = 'Pull01.jeremysbrain.org'
            ProviderName = 'Microsoft RSA SChannel Cryptographic Provider'
            AutoRenew = $true
            Exportable = $true
            FriendlyName = 'PullServerCert'
            KeyUsage = '0xa0'
            RequestType = 'PKCS10'
            KeyType = 'RSA'
            CertificateTemplate = 'WebServer'
            DependsOn = '[AdcsWebEnrollment]InstallWebEnrollment'
        }

I've verified that the .inf file does exist in the \Windows\Temp folder.

Verbose output below:
VERBOSE: [CERT01]: LCM:  [ Start  Resource ]  [[CertReq]PullCert]
VERBOSE: [CERT01]: LCM:  [ Start  Test     ]  [[CertReq]PullCert]
VERBOSE: [CERT01]:                            [[CertReq]PullCert] Starting to locate CA.
VERBOSE: [CERT01]:                            [[CertReq]PullCert] Using the following container to look for CA
candidates: 'LDAP://CN=CDP,CN=Public Key Services,CN=Services,CN=Configuration,DC=jeremysbrain,DC=org'
VERBOSE: [CERT01]:                            [[CertReq]PullCert] Starting to ping CA.
VERBOSE: [CERT01]:                            [[CertReq]PullCert] certutil exited with code 0 and the following output:
 Connecting to Cert01\jeremysbrain-CERT01-CA ...
Server "jeremysbrain-CERT01-CA" ICertRequest2 interface is alive (0ms)
CertUtil: -ping command completed successfully.
VERBOSE: [CERT01]:                            [[CertReq]PullCert] Certificate authority 'Cert01jeremysbrain-CERT01-CA'
is online.
VERBOSE: [CERT01]:                            [[CertReq]PullCert] Found certificate authority
'Cert01jeremysbrain-CERT01-CA'.
VERBOSE: [CERT01]:                            [[CertReq]PullCert] Test-TargetResource: Testing Certificate with Subject
 'CN=Pull01, , OU=IT, O=JeremysBrain, L=Chino, S=CA, C=US' issued by Cert01\jeremysbrain-CERT01-CA.
VERBOSE: [CERT01]:                            [[CertReq]PullCert] Test-TargetResource: No valid certificate found with
subject 'CN=Pull01, , OU=IT, O=JeremysBrain, L=Chino, S=CA, C=US' issued by Cert01\jeremysbrain-CERT01-CA.
VERBOSE: [CERT01]: LCM:  [ End    Test     ]  [[CertReq]PullCert]  in 0.3900 seconds.
VERBOSE: [CERT01]: LCM:  [ Start  Set      ]  [[CertReq]PullCert]
VERBOSE: [CERT01]:                            [[CertReq]PullCert] Starting to locate CA.
VERBOSE: [CERT01]:                            [[CertReq]PullCert] Using the following container to look for CA
candidates: 'LDAP://CN=CDP,CN=Public Key Services,CN=Services,CN=Configuration,DC=jeremysbrain,DC=org'
VERBOSE: [CERT01]:                            [[CertReq]PullCert] Starting to ping CA.
VERBOSE: [CERT01]:                            [[CertReq]PullCert] certutil exited with code 0 and the following output:
 Connecting to Cert01\jeremysbrain-CERT01-CA ...
Server "jeremysbrain-CERT01-CA" ICertRequest2 interface is alive (15ms)
CertUtil: -ping command completed successfully.
VERBOSE: [CERT01]:                            [[CertReq]PullCert] Certificate authority 'Cert01jeremysbrain-CERT01-CA'
is online.
VERBOSE: [CERT01]:                            [[CertReq]PullCert] Found certificate authority
'Cert01jeremysbrain-CERT01-CA'.
VERBOSE: [CERT01]:                            [[CertReq]PullCert] Set-TargetResource: Starting Certificate request with
 Subject 'CN=Pull01, , OU=IT, O=JeremysBrain, L=Chino, S=CA, C=US' issued by Cert01\jeremysbrain-CERT01-CA.
VERBOSE: [CERT01]:                            [[CertReq]PullCert] Set-TargetResource: Creating certificate request
'C:\Windows\TEMP\xCertReq-cdeb7584-e181-423c-a08d-fded9f0b686c.req' from
'C:\Windows\TEMP\xCertReq-cdeb7584-e181-423c-a08d-fded9f0b686c.inf'.
VERBOSE: [CERT01]:                            [[CertReq]PullCert] Set-TargetResource: Create certificate request
result: Active Directory Enrollment Policy
  {53B155A9-742B-4F44-A0D2-FC26F0362879}
  ldap:
**Certificate Request Processor: Invalid provider specified. 0x80090013 (-2146893805 NTE_BAD_PROVIDER)
VERBOSE: [CERT01]: LCM:  [ End    Set      ]  [[CertReq]PullCert]  in 0.3440 seconds.
PowerShell DSC resource MSFT_CertReq  failed to execute Set-TargetResource functionality with error message:
System.InvalidOperationException: Certificate Request file
'C:\Windows\TEMP\xCertReq-cdeb7584-e181-423c-a08d-fded9f0b686c.req' not found.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost**

VERBOSE: [CERT01]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 5.758 seconds

**Comment by jeremysbrain** [comment]
Problem solved...
Soltion was to add double quotes around the Provider Name like below:
ProviderName = '"Microsoft RSA SChannel Cryptographic Provider"'

Probably a rookie mistake.

**Comment by PlagueHO** [comment]
Thanks for updating @jeremysbrain - although I'd actually say that we shouldn't need the extra quotes around the provider name. It would be better if they were automatically added.

I might add an issue to actually do this.

**Comment by PlagueHO** [comment]
I've added an issue to track this change: https://github.com/PowerShell/CertificateDsc/issues/185
