### ISSUE TITLE
CertReq: 'ReferenceSubject'. The argument is null or empty

### ISSUE THREAD

**Issue by andystumph** [PowerShell/CertificateDsc#190]
#### Details of the scenario you tried and the problem that is occurring
When Test-TargetResource is run, it tries to compare certificates in the existing cert store against the new cert request. If there is a certificate in the store that does NOT have a Subject, the script errors out.

Code:
$cert = Get-Childitem -Path Cert:\LocalMachine\My |
        Where-Object -FilterScript {
            (Compare-CertificateSubject -ReferenceSubject $_.Subject -DifferenceSubject $Subject) -and `
            $_.Issuer.split(',')[0] -eq "CN=$CARootName"
    }

#### Verbose logs showing the problem
VERBOSE: [Server]: LCM:  [ Start  Resource ]  [[CertReq]SCOMCert]
VERBOSE: [Server]: LCM:  [ Start  Test     ]  [[CertReq]SCOMCert]
VERBOSE: [Server]:                            [[CertReq]SCOMCert] Test-TargetResource: Testing Certificate with Subject 'CN=Server' issued by MyCA.
Cannot validate argument on parameter 'ReferenceSubject'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Compare-CertificateSubject
    + PSComputerName        : localhost

VERBOSE: [Server]:                            [[CertReq]SCOMCert] Test-TargetResource: No valid certificate found with subject 'CN=Server' issued by MyCA.
VERBOSE: [Server]: LCM:  [ End    Test     ]  [[CertReq]SCOMCert]  in 0.3610 seconds.
The PowerShell DSC resource '[CertReq]SCOMCert' with SourceInfo '::37::9::CertReq' threw one or more non-terminating errors while running the Test-TargetResource functionality. These errors are logged to the ETW channel called
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
#### Suggested solution to the issue
Check to make sure the existing cert has a valid subject before doing the compare.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
CertReq SCOMCert
        {
            Subject = "$NodeName"
            SubjectAltName = "dns=$($NodeName).$($dscDomainName)&dns=$($NodeName)"
            CAServerFQDN = "$SubCAFQDN"
            CARootName = "$SubCAName"
            Exportable = $true
            AutoRenew = $true
            ProviderName = '"Microsoft RSA SChannel Cryptographic Provider"'
            CertificateTemplate = 'SCOMCertificate'
            FriendlyName = $FriendlyName
            Credential = $dscDomainAdmin
        }
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2848.amd64fre.rs1_release.190305-1856
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.14393.2828
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2828
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
ModuleType Version    Name
---------- -------    ----
Manifest   4.5.0.0    CertificateDsc

**Comment by PlagueHO** [comment]
Great catch @andystumph - looks like an easy fix. I'll get onto it ASAP. Thanks for raising this one.
