### ISSUE TITLE
CertificateImport: "Cannot find the original signer" error chain of certificates

### ISSUE THREAD

**Issue by alphakilo45** [PowerShell/CertificateDsc#192]
ISSUE TITLE:
CertificateImport: "Cannot find the original signer" error chain of certificates

ISSUE DESCRIPTION (this template):

#### Details of the scenario you tried and the problem that is occurring
When attempting to use the CertificateImport resource to import a p7b, we are getting the error "Cannot find the original signer." if the p7b includes a chain of certificates where the parent certificates in the chain have not already been imported.  This issue appeared between versions 4.2.0 and 4.4.0 of CertificateDsc.

#### Verbose logs showing the problem
VERBOSE: [MACHINE]]: LCM:  [ Start  Resource ]  [[CertificateImport]ImportCertificate]
VERBOSE: [MACHINE]: LCM:  [ Start  Test     ]  [[CertificateImport]ImportCertificate]
VERBOSE: [MACHINE]:                            [[CertificateImport]ImportCertificate] Get-TargetResource: Getting Certificate existence 'Thumbprint' in 'Cert:\LocalMachine\My'.
VERBOSE: [MACHINE]:                            [[CertificateImport]ImportCertificate] Test-TargetResource: Testing Certificate 'Thumbprint' existence in 'Cert:\LocalMachine\My'.
VERBOSE: [MACHINE]: LCM:  [ End    Test     ]  [[CertificateImport]ImportCertificate]  in 3.0940 seconds.
VERBOSE: [MACHINE]: LCM:  [ Start  Set      ]  [[CertificateImport]ImportCertificate]
VERBOSE: [MACHINE]:                            [[CertificateImport]ImportCertificate] Set-TargetResource: Setting Certificate 'Thumbprint' existence in 'Cert:\LocalMachine\My'.
VERBOSE: [MACHINE]:                            [[CertificateImport]ImportCertificate] Performing the operation "Set-TargetResource" on target "Importing certificate 'C:\temp\certificate.p7b' into 'Cert:\LocalMachine\My'".
VERBOSE: [MACHINE]:                            [[CertificateImport]ImportCertificate] Set-TargetResource: Importing Certificate 'C:\temp\certificate.p7b' into 'Cert:\LocalMachine\My'.
Exception calling "Import" with "1" argument(s): "Cannot find the original signer."
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : CryptographicException
    + PSComputerName        : machine.localdomain.com
 
Exception calling "Add" with "1" argument(s): "pCertContext is an invalid handle."
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : CryptographicException
    + PSComputerName        : machine.localdomain.com

#### Suggested solution to the issue
It appears this issue was introduced by the fix to Issue PowerShell/CertificateDsc#161 where all imports now use Import-CertificateEx.  If I run the PowerShell commands in that cmdlet manually I see the same error.  

When I switched to using X509Certificate2Collection instead of X509Certificate2 and called $certStore.AddRange instead of $certStore.Add I was able to import the .p7b successfully.

```powershell
$location = Split-Path -Path (Split-Path -Path $CertStoreLocation -Parent) -Leaf
$store = Split-Path -Path $CertStoreLocation -Leaf

$cert = New-Object -TypeName System.Security.Cryptography.X509Certificates.X509Certificate2Collection
$cert.Import($FilePath)

$certStore = New-Object `
	-TypeName System.Security.Cryptography.X509Certificates.X509Store `
	-ArgumentList ($store, $location)

$certStore.Open('MaxAllowed')
$certStore.AddRange($cert)
$certStore.Close()
```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
CertificateImport "ImportCertificate" {
    Thumbprint = "<thumbprint>"
    Path       = "<Path to a .p7b cert with a chain of certs, none of which are currently imported"
    Location   = "LocalMachine"
    Store      = "My"
}
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2016 Datacenter
OsOperatingSystemSKU : DatacenterServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 14393.2848.amd64fre.rs1_release.190305-1856
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
PSVersion                      5.1.14393.2828                                                                             
PSEdition                      Desktop                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                    
BuildVersion                   10.0.14393.2828                                                                            
CLRVersion                     4.0.30319.42000                                                                            
WSManStackVersion              3.0                                                                                        
PSRemotingProtocolVersion      2.3                                                                                        
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
4.4.0

**Comment by PlagueHO** [comment]
Hi @alphakilo45 - thank you for raising this and the great info and debugging. I suspect the use of X509Certificate2Collection is a better approach anyway as P7B and PKCS12 both can contain the entire certificate chain. I'll see if I can get this fix in over the weekend.
