### ISSUE TITLE
CertReq: AutoRenew (Question)

### ISSUE THREAD

**Issue by SwarfegaGit** [PowerShell/CertificateDsc#205]
I wrote a configuration opting for AutoRenew to be $true.  However, my LCM is set to 'ApplyAndMonitor'.  My question is will auto-renew still work or only if my LCM is set to 'ApplyAndAutoCorrect'?

**Comment by PlagueHO** [comment]
Hi @SwarfegaGit - the AutoRenew mechanism is handled by the resource itself. So this requires 'ApplyAndAutoCorrect' to be used or some other trigger to regularly reapply the configuration.

**Comment by SwarfegaGit** [comment]
Great, thanks.
