### ISSUE TITLE
CertificateDsc.Common: Find-Certificate has a typo in a code path

### ISSUE THREAD

**Issue by johlju** [PowerShell/CertificateDsc#208]
There is a typo in the parameter name `ArgumentName` so if the certificate path is not valid it would generate the wrong error message. 

The description has a typo too. 

https://github.com/PowerShell/CertificateDsc/blob/72751a97f38f6e40618930b14fd62e966f847c9e/Modules/CertificateDsc.Common/CertificateDsc.Common.psm1#L741-L744

**Comment by johlju** [comment]
*Personal note: When a unit test is added that tests this change, that unit test should be added to `xWebAdministration.Common.Tests.ps1` over in the xWebAdministration module as well.*

**Comment by PlagueHO** [comment]
Good catch @johlju!
